### **Load your dataset**

In [1]:
from google.colab import files
uploaded = files.upload()  # choose your CSV file

Saving sales_data.csv to sales_data.csv

### **Executing first few rows**

In [2]:
import pandas as pd

df = pd.read_csv("sales_data.csv")
df.head()  # see first few rows

       Date  Total_Users  Total_Orders  Total_Sales
0  1/1/2024          126            26        11596
1  1/1/2024          164            49        31801
2  1/2/2024          130            26        18148
3  1/3/2024          128            36        18792
4  1/3/2024          163            59        40002

In [8]:
print(df['Date'].head(20))  # see first 20 rows

0      1/1/2024
1      1/1/2024
2      1/2/2024
3      1/3/2024
4      1/3/2024
5      1/5/2024
6      1/5/2024
7      1/6/2024
8      1/6/2024
9      1/7/2024
10     1/8/2024
11    1/10/2024
12    1/10/2024
13    1/11/2024
14    1/13/2024
15    1/13/2024
16    1/14/2024
17    1/15/2024
18    1/17/2024
19    1/17/2024
Name: Date, dtype: object

### **Generate again random dates**

In [9]:
import pandas as pd
import numpy as np

# Generate 60 days from Jan 1, 2024
dates = pd.date_range(start='2024-01-01', periods=60, freq='D')

# Create random dataset
np.random.seed(42)
df = pd.DataFrame({
    'Date': dates,
    'total_users': np.random.randint(50, 200, size=60),
    'total_orders': np.random.randint(30, 150, size=60),
    'total_sales': np.random.randint(500, 5000, size=60)
})

df.head()

        Date  total_users  total_orders  total_sales
0 2024-01-01          152           122         3604
1 2024-01-02          142            92         2954
2 2024-01-03           64            47         4145
3 2024-01-04          156           119         1304
4 2024-01-05          121            73         3231

### **Convert date column and extract features**

In [10]:
# Make sure Date column is datetime
df['Date'] = pd.to_datetime(df['Date'])

# Extract useful features from date
df['day'] = df['Date'].dt.day
df['month'] = df['Date'].dt.month
df['weekday'] = df['Date'].dt.weekday  # Monday=0, Sunday=6

# Check the dataframe
df.head()

        Date  total_users  total_orders  total_sales  day  month  weekday
0 2024-01-01          152           122         3604    1      1        0
1 2024-01-02          142            92         2954    2      1        1
2 2024-01-03           64            47         4145    3      1        2
3 2024-01-04          156           119         1304    4      1        3
4 2024-01-05          121            73         3231    5      1        4

### **Prepare Input Features and Target**

In [11]:
# Input features (X) and target (y)
X = df[['total_users', 'total_orders', 'day', 'month', 'weekday']]
y = df['total_sales']

### **Split Data into Training and Testing**

In [12]:
from sklearn.model_selection import train_test_split

# 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### **Train a Linear regression Model**

In [13]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

### **Test Predictions**

In [14]:
# Predict on test data
y_pred = model.predict(X_test)

# Compare actual vs predicted
import pandas as pd
pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

    Actual    Predicted
0     3604  2406.867793
5     3273  2908.407139
36    2029  3013.241054
45    4913  2831.193615
13    4988  2633.562910
54    2353  3254.541751
33    1863  2713.785874
48    2498  3220.774543
12    1370  2766.787524
57    3957  2800.970542
46    4248  2974.224223
50    4243  2940.522431

### **Evaluate Model Accuracy**

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"Mean Absolute Error: {mae}")
print(f"Root Mean Squared Error: {rmse}")

Mean Absolute Error: 1215.5318410316088
Root Mean Squared Error: 1325.3133269465377

### **Predict Sales Trend**

In [16]:
trend = []
for i in range(len(y_pred)):
    if i == 0:
        trend.append("Stable")
    else:
        if y_pred[i] > y_pred[i-1]:
            trend.append("Up")
        elif y_pred[i] < y_pred[i-1]:
            trend.append("Down")
        else:
            trend.append("Stable")

# Add predictions and trend to test dataframe
df_test = X_test.copy()
df_test['Predicted_sales'] = y_pred
df_test['Trend'] = trend
df_test.head()

    total_users  total_orders  day  month  weekday  Predicted_sales   Trend
0           152           122    1      1        0      2406.867793  Stable
5            70            63    6      1        5      2908.407139      Up
36           67            38    6      2        1      3013.241054      Up
45          133           110   15      2        3      2831.193615    Down
13          180           101   14      1        6      2633.562910    Down

### **Save your trained model**

In [17]:
import pickle

# Save the trained model to a file
with open("sales_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully!")

Model saved successfully!

### **Test the model with new data**

In [18]:
# Example new data
new_data = pd.DataFrame({
    'total_users': [120],
    'total_orders': [85],
    'day': [10],
    'month': [2],
    'weekday': [5]
})

# Predict
predicted_sales = model.predict(new_data)
print(f"Predicted Sales: {predicted_sales[0]}")

Predicted Sales: 2939.737392572434

### **Create sales trend for prediction**

In [19]:
# Compare with previous day (or any reference)
previous_sales = 1000  # Example previous day
if predicted_sales[0] > previous_sales:
    trend = "Up"
elif predicted_sales[0] < previous_sales:
    trend = "Down"
else:
    trend = "Stable"

print(f"Sales Trend: {trend}")

Sales Trend: Up

### **Install required libraries**

In [36]:
!pip install flask
!pip install pyngrok

Requirement already satisfied: flask in /usr/local/lib/python3.12/dist-packages (3.1.2)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from flask) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from flask) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from flask) (3.1.5)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.12/dist-packages (7.5.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)

### **Authentication ngrok account**

In [37]:
!ngrok authtoken 39RGbWX2T2l5VFqiai7gvV6agpD_5Xegd4GXW3Uy2JKwhzLe5

Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml

### **Import Libraries and trained model**

In [38]:
from flask import Flask, request, jsonify
from pyngrok import ngrok
import pickle
import pandas as pd

# Load the trained model
with open("sales_model.pkl", "rb") as f:
    model = pickle.load(f)

### **Initialize Flask App and Create ngrok Public URL**

In [39]:
app = Flask(__name__)

# Connect ngrok to port 5000 and get public URL
public_url = ngrok.connect(5000)
print("Public URL:", public_url)

Public URL: NgrokTunnel: "https://preparliamentary-nakesha-inferrible.ngrok-free.dev" -> "http://localhost:5000"

### **Define API Endpoint /predict-sales**

In [ ]:
@app.route('/predict-sales', methods=['POST'])
def predict_sales():
    data = request.json  # get JSON input
    df = pd.DataFrame(data, index=[0])  # convert to DataFrame

    # Predict sales
    prediction = model.predict(df)[0]

    # Calculate trend (optional)
    previous_sales = data.get('previous_sales', prediction)
    if prediction > previous_sales:
        trend = "Up"
    elif prediction < previous_sales:
        trend = "Down"
    else:
        trend = "Stable"

    # Return JSON response
    return jsonify({'predicted_sales': float(prediction), 'trend': trend})